// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.5.1
// source: protopb/bidipb.proto

package protopb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num int64 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protopb_bidipb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_protopb_bidipb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_protopb_bidipb_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Maxstream int64 `protobuf:"varint,1,opt,name=maxstream,proto3" json:"maxstream,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protopb_bidipb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_protopb_bidipb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_protopb_bidipb_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetMaxstream() int64 {
	if x != nil {
		return x.Maxstream
	}
	return 0
}

var File_protopb_bidipb_proto protoreflect.FileDescriptor

var file_protopb_bidipb_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x70, 0x62, 0x2f, 0x62, 0x69, 0x64, 0x69, 0x70, 0x62,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x70, 0x62, 0x22,
	0x1b, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0x28, 0x0a, 0x08,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x61, 0x78, 0x73,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6d, 0x61, 0x78,
	0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x32, 0x46, 0x0a, 0x0e, 0x4d, 0x61, 0x78, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x42, 0x69, 0x64, 0x69, 0x12, 0x34, 0x0a, 0x07, 0x4d, 0x61, 0x78, 0x42,
	0x69, 0x64, 0x69, 0x12, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x70, 0x62, 0x2e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x70, 0x62, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x09,
	0x5a, 0x07, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_protopb_bidipb_proto_rawDescOnce sync.Once
	file_protopb_bidipb_proto_rawDescData = file_protopb_bidipb_proto_rawDesc
)

func file_protopb_bidipb_proto_rawDescGZIP() []byte {
	file_protopb_bidipb_proto_rawDescOnce.Do(func() {
		file_protopb_bidipb_proto_rawDescData = protoimpl.X.CompressGZIP(file_protopb_bidipb_proto_rawDescData)
	})
	return file_protopb_bidipb_proto_rawDescData
}

var file_protopb_bidipb_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protopb_bidipb_proto_goTypes = []interface{}{
	(*Request)(nil),  // 0: protopb.Request
	(*Response)(nil), // 1: protopb.Response
}
var file_protopb_bidipb_proto_depIdxs = []int32{
	0, // 0: protopb.MaxServiceBidi.MaxBidi:input_type -> protopb.Request
	1, // 1: protopb.MaxServiceBidi.MaxBidi:output_type -> protopb.Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protopb_bidipb_proto_init() }
func file_protopb_bidipb_proto_init() {
	if File_protopb_bidipb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protopb_bidipb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protopb_bidipb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protopb_bidipb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protopb_bidipb_proto_goTypes,
		DependencyIndexes: file_protopb_bidipb_proto_depIdxs,
		MessageInfos:      file_protopb_bidipb_proto_msgTypes,
	}.Build()
	File_protopb_bidipb_proto = out.File
	file_protopb_bidipb_proto_rawDesc = nil
	file_protopb_bidipb_proto_goTypes = nil
	file_protopb_bidipb_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MaxServiceBidiClient is the client API for MaxServiceBidi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MaxServiceBidiClient interface {
	MaxBidi(ctx context.Context, opts ...grpc.CallOption) (MaxServiceBidi_MaxBidiClient, error)
}

type maxServiceBidiClient struct {
	cc grpc.ClientConnInterface
}

func NewMaxServiceBidiClient(cc grpc.ClientConnInterface) MaxServiceBidiClient {
	return &maxServiceBidiClient{cc}
}

func (c *maxServiceBidiClient) MaxBidi(ctx context.Context, opts ...grpc.CallOption) (MaxServiceBidi_MaxBidiClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MaxServiceBidi_serviceDesc.Streams[0], "/protopb.MaxServiceBidi/MaxBidi", opts...)
	if err != nil {
		return nil, err
	}
	x := &maxServiceBidiMaxBidiClient{stream}
	return x, nil
}

type MaxServiceBidi_MaxBidiClient interface {
	Send(*Request) error
	Recv() (*Response, error)
	grpc.ClientStream
}

type maxServiceBidiMaxBidiClient struct {
	grpc.ClientStream
}

func (x *maxServiceBidiMaxBidiClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *maxServiceBidiMaxBidiClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MaxServiceBidiServer is the server API for MaxServiceBidi service.
type MaxServiceBidiServer interface {
	MaxBidi(MaxServiceBidi_MaxBidiServer) error
}

// UnimplementedMaxServiceBidiServer can be embedded to have forward compatible implementations.
type UnimplementedMaxServiceBidiServer struct {
}

func (*UnimplementedMaxServiceBidiServer) MaxBidi(MaxServiceBidi_MaxBidiServer) error {
	return status.Errorf(codes.Unimplemented, "method MaxBidi not implemented")
}

func RegisterMaxServiceBidiServer(s *grpc.Server, srv MaxServiceBidiServer) {
	s.RegisterService(&_MaxServiceBidi_serviceDesc, srv)
}

func _MaxServiceBidi_MaxBidi_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MaxServiceBidiServer).MaxBidi(&maxServiceBidiMaxBidiServer{stream})
}

type MaxServiceBidi_MaxBidiServer interface {
	Send(*Response) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type maxServiceBidiMaxBidiServer struct {
	grpc.ServerStream
}

func (x *maxServiceBidiMaxBidiServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *maxServiceBidiMaxBidiServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _MaxServiceBidi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protopb.MaxServiceBidi",
	HandlerType: (*MaxServiceBidiServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "MaxBidi",
			Handler:       _MaxServiceBidi_MaxBidi_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "protopb/bidipb.proto",
}
